import os
Import('env')

VariantDir('build', '.', duplicate=0)

windows_examples = ['2.c', '11.c']
linux_examples = ['9.c', '10.c']

for root, dirs, files in os.walk('./'):
	for file in files:
		if((len(file) - 2) == (file.find('.c'))):

			if(os.name == 'nt' and file in linux_examples):
				continue
			if(os.name != 'nt' and file in windows_examples):
				continue

			env.Program('build/'+file)
