import os
Import('env')

VariantDir('build', '.', duplicate=0)

if(os.name != 'nt'):
	env.Program(['build/2.c', 'build/arplib.c'])

env.Program(['build/1.c', 'build/arplib.c'])
env.Program(['build/3.c', 'build/arplib.c'])

